# Generated by Django 5.1 on 2024-08-29 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='healmetrics',
            old_name='calorise',
            new_name='calories_consumed',
        ),
        migrations.RenameField(
            model_name='healmetrics',
            old_name='steps',
            new_name='exercise_min',
        ),
        migrations.AddField(
            model_name='healmetrics',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='healmetrics',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='healmetrics',
            name='water_intake',
            field=models.FloatField(default=0.0, help_text='wate intake in litres'),
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight', 'Weight'), ('calories', 'Calories'), ('exercise', 'Exercise')], max_length=50)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(default=0)),
                ('start_date', models.DateField()),
                ('end_time', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
